// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvH9P5QQpStRPSHiee5fUeeWdpU9kPv5c',
    appId: '1:683992525731:web:6ee83551ee6f3a5dbbc816',
    messagingSenderId: '683992525731',
    projectId: 'addvanced-academy',
    authDomain: 'addvanced-academy.firebaseapp.com',
    storageBucket: 'addvanced-academy.firebasestorage.app',
    measurementId: 'G-FXJP6CM88C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvsaUVPsvs_-9GY8oeLMKOcNfmD2i5sFA',
    appId: '1:683992525731:android:a910f88bad72c260bbc816',
    messagingSenderId: '683992525731',
    projectId: 'addvanced-academy',
    storageBucket: 'addvanced-academy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHROUt4wNntUl3WzUJj5PtCprnJo4mFB8',
    appId: '1:683992525731:ios:b1d88b93d610606cbbc816',
    messagingSenderId: '683992525731',
    projectId: 'addvanced-academy',
    storageBucket: 'addvanced-academy.firebasestorage.app',
    iosBundleId: 'com.example.advancedAcademy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHROUt4wNntUl3WzUJj5PtCprnJo4mFB8',
    appId: '1:683992525731:ios:b1d88b93d610606cbbc816',
    messagingSenderId: '683992525731',
    projectId: 'addvanced-academy',
    storageBucket: 'addvanced-academy.firebasestorage.app',
    iosBundleId: 'com.example.advancedAcademy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvH9P5QQpStRPSHiee5fUeeWdpU9kPv5c',
    appId: '1:683992525731:web:d4a4db4fda79238abbc816',
    messagingSenderId: '683992525731',
    projectId: 'addvanced-academy',
    authDomain: 'addvanced-academy.firebaseapp.com',
    storageBucket: 'addvanced-academy.firebasestorage.app',
    measurementId: 'G-9V06XCQXZF',
  );
}
